name: CI/CD Pipeline for Streamlit and Hugging Face

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  # Make sure you have pytest in your requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Streamlit
        run: |
          pip install streamlit

      - name: Deploy to Hugging Face
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HF_TOKEN }}  # Use the correct secret name
        run: |
          # Assuming you have a deployment script to deploy your app
          streamlit run your_app.py --server.port 8501 --server.address 0.0.0.0